import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft, Shield, Database, Cloud, Eye, Lock, Users, RefreshCw, Mail } from "lucide-react";
import CosmicBackground from "@/components/CosmicBackground";

const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: 0.15 + i * 0.08, duration: 0.5, ease: "easeOut" },
  }),
};

const sections = [
  {
    icon: Database,
    number: "1",
    title: "Information We Collect",
    content: (
      <>
        <p className="text-muted-foreground leading-relaxed mb-4">
          MAX Desktop Companion is designed to respect your privacy. Almost all data generated by the application stays entirely on your local machine.
        </p>

        <h4 className="text-base font-heading font-semibold text-foreground mb-2">Fully Local Data</h4>
        <p className="text-muted-foreground leading-relaxed mb-3">
          The following data is saved <strong className="text-foreground/80">only on your local device</strong> (in your local <code className="text-primary/70 bg-primary/5 px-1.5 py-0.5 rounded text-xs font-mono">AppData</code> folder) and is never transmitted to our servers or any third parties:
        </p>
        <ul className="space-y-2 mb-5">
          {[
            ["User Settings & Progression", "User ID, daily streaks, achievements (user_data.json), and preferences (tuning.json)."],
            ["Clipboard History", "Up to 5 recent clipboard items accessed via the 'Pouch' feature (pouch.json)."],
            ["Error Logs", "Crash logs generated if the app experiences an error (crash.log)."],
            ["Screen Captures & Recordings", "Saved directly to your local desktop (MAX Captures folder) and never uploaded."],
          ].map(([label, desc]) => (
            <li key={label} className="flex items-start gap-2 text-muted-foreground text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary/50 shrink-0" />
              <span><strong className="text-foreground/70">{label}:</strong> {desc}</span>
            </li>
          ))}
        </ul>

        <h4 className="text-base font-heading font-semibold text-foreground mb-2">Cloud Data (Firebase Sync — Optional)</h4>
        <p className="text-muted-foreground leading-relaxed mb-3">
          If your computer is connected to the internet, MAX securely syncs a minimal amount of anonymized data to Firebase. This is explicitly to allow the referral and achievement system to function:
        </p>
        <ul className="space-y-2 mb-5">
          {[
            ["Anonymized UUID", "A randomly generated User ID that cannot be tied to your personal identity, email, or device hardware."],
            ["Referral Counts", "The numeric total of times your referral code has been used."],
            ["Unlocked Achievements", 'Simple text strings indicating which easter eggs or features you have discovered (e.g., "first_throw").'],
          ].map(([label, desc]) => (
            <li key={label} className="flex items-start gap-2 text-muted-foreground text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-accent/50 shrink-0" />
              <span><strong className="text-foreground/70">{label}:</strong> {desc}</span>
            </li>
          ))}
        </ul>

        <h4 className="text-base font-heading font-semibold text-foreground mb-2">What We DO NOT Collect</h4>
        <p className="text-muted-foreground leading-relaxed mb-3">
          MAX <strong className="text-foreground/80">does not</strong> collect, store, or transmit:
        </p>
        <ul className="space-y-2">
          {[
            "Your browsing history or website activity.",
            "The contents of your files, folders, or windows.",
            "Any passwords (e.g., the WiFi tool reads your saved local password to show it to you, but never stores or sends it).",
            "Your keystrokes (the cheat code listener only locally matches specific predefined words).",
            "Analytics, tracking cookies, telemetry, or personal identity information.",
            "Camera or microphone data.",
          ].map((item) => (
            <li key={item} className="flex items-start gap-2 text-muted-foreground text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-destructive/50 shrink-0" />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    icon: Eye,
    number: "2",
    title: "How We Use Information",
    content: (
      <p className="text-muted-foreground leading-relaxed">
        The minimal anonymized data we sync (UUID, referrals, achievements) is used strictly to provide the core progression features of the app—specifically, tracking how many referrals you have made so you can unlock cosmetic items (like hats or different glow colors).
      </p>
    ),
  },
  {
    icon: Cloud,
    number: "3",
    title: "Third-Party Services",
    content: (
      <>
        <p className="text-muted-foreground leading-relaxed mb-3">
          MAX Desktop Companion interacts with the following external services for specific functionalities:
        </p>
        <ul className="space-y-2">
          {[
            ['IPify (api.ipify.org)', 'When you explicitly request your Public IP address via the "Info > IP" tool, the app makes a single request to IPify. Your IP is not stored by us.'],
            ["Firebase", "Used solely for syncing the anonymized referral and achievements data mentioned above."],
          ].map(([label, desc]) => (
            <li key={label} className="flex items-start gap-2 text-muted-foreground text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary/50 shrink-0" />
              <span><strong className="text-foreground/70">{label}:</strong> {desc}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    icon: Users,
    number: "4",
    title: "Children's Privacy",
    content: (
      <p className="text-muted-foreground leading-relaxed">
        Our application does not intentionally collect any personal information from children under the age of 13. Given our minimal, anonymized data footprint, we do not require age verification, as we do not gather identifiable personal data.
      </p>
    ),
  },
  {
    icon: Lock,
    number: "5",
    title: "User Controls",
    content: (
      <>
        <p className="text-muted-foreground leading-relaxed mb-3">You have full control over your data:</p>
        <ul className="space-y-2">
          {[
            <>Settings and progression can be wiped directly by deleting the local <code className="text-primary/70 bg-primary/5 px-1.5 py-0.5 rounded text-xs font-mono">user_data.json</code> and <code className="text-primary/70 bg-primary/5 px-1.5 py-0.5 rounded text-xs font-mono">tuning.json</code> files in your <code className="text-primary/70 bg-primary/5 px-1.5 py-0.5 rounded text-xs font-mono">{'<AppData>/ProjectMAX'}</code> directory.</>,
            "For issues regarding your synced, anonymized Firebase data, you may wipe or disconnect following our documentation.",
            "The application will function fully offline, preventing any data from being synced to Firebase if you choose.",
          ].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-muted-foreground text-sm leading-relaxed">
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary/50 shrink-0" />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    icon: Shield,
    number: "6",
    title: "Security",
    content: (
      <p className="text-muted-foreground leading-relaxed">
        We take reasonable measures to protect your anonymized data in transit. However, since the vast majority of your data remains solely on your local hard drive, its primary security relies on your computer's own operating system and security practices.
      </p>
    ),
  },
  {
    icon: RefreshCw,
    number: "7",
    title: "Changes to This Privacy Policy",
    content: (
      <p className="text-muted-foreground leading-relaxed">
        We may periodically update this Privacy Policy to reflect new features or capabilities. If significant changes are made concerning how data is collected or used, we will update the "Effective Date" at the top of this document.
      </p>
    ),
  },
  {
    icon: Mail,
    number: "8",
    title: "Contact Us",
    content: (
      <p className="text-muted-foreground leading-relaxed">
        If you have any questions or concerns about this privacy policy or our data practices, please{" "}
        <a
          href="https://github.com/M-SRIKAR-VARDHAN/MAX-Desktop-Companion/issues"
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary hover:text-primary/80 underline underline-offset-4 transition-colors"
        >
          create an issue on our GitHub repository
        </a>
        .
      </p>
    ),
  },
];

const PrivacyPolicy = () => {
  return (
    <div className="relative min-h-screen bg-[#03030a]">
      <CosmicBackground />

      <div className="relative z-10">
        {/* Top navigation */}
        <nav className="sticky top-0 z-50 border-b border-border/50 bg-background/60 backdrop-blur-xl">
          <div className="container max-w-4xl mx-auto px-4 py-4 flex items-center gap-3">
            <Link
              to="/"
              className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors font-heading"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>
          </div>
        </nav>

        {/* Content */}
        <main className="container max-w-4xl mx-auto px-4 py-16 md:py-24">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/20 bg-primary/5 text-primary text-xs font-heading font-medium tracking-wider uppercase mb-6">
              <Shield className="w-3.5 h-3.5" />
              Privacy Policy
            </div>
            <h1 className="text-4xl md:text-5xl font-heading font-bold text-foreground mb-4">
              Privacy Policy for{" "}
              <span className="text-primary text-glow-cyan">MAX</span>
            </h1>
            <p className="text-muted-foreground max-w-xl mx-auto leading-relaxed">
              This Privacy Policy describes how the MAX Desktop Companion application handles your data. We are committed to protecting your privacy and being fully transparent about any data our application processes.
            </p>
            <p className="text-muted-foreground/50 text-sm mt-4 font-mono">
              Effective Date: April 3, 2026
            </p>
          </motion.div>

          {/* Sections */}
          <div className="space-y-8">
            {sections.map((section, i) => (
              <motion.section
                key={section.number}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-50px" }}
                variants={sectionVariants}
                className="group relative rounded-2xl border border-border/50 bg-card/40 backdrop-blur-sm p-6 md:p-8 hover:border-primary/20 transition-colors duration-300"
              >
                {/* Hover glow */}
                <div className="absolute inset-0 rounded-2xl bg-primary/[0.02] opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />

                <div className="relative">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="flex items-center justify-center w-9 h-9 rounded-lg bg-primary/10 text-primary shrink-0">
                      <section.icon className="w-4.5 h-4.5" />
                    </div>
                    <h2 className="text-xl md:text-2xl font-heading font-bold text-foreground">
                      <span className="text-primary/40 mr-1.5">{section.number}.</span>
                      {section.title}
                    </h2>
                  </div>
                  {section.content}
                </div>
              </motion.section>
            ))}
          </div>

          {/* Footer note */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.3 }}
            className="mt-16 text-center"
          >
            <p className="text-muted-foreground/30 text-xs font-heading italic">
              This policy is provided in accordance with the requirements of the Microsoft Store.
            </p>
          </motion.div>
        </main>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
